### ISSUE TITLE
Question regarding the sjmisc -> sjlabelled transition

### ISSUE THREAD

**Issue by methodds** [strengejacke/sjlabelled#1]
Hi, 
I just installed sjmisc, sjPlot and sjlabelled from CRAN and noticed that some functions still use label function from sjmisc, e.g. `sjt.corr()` (line 29).
The problem with this is that even when a new user properly loads sjlabelled, the message

> *This function will be removed in future versions of sjmisc and has been moved to package 'sjlabelled'.  Please use sjlabelled::get_label() instead.This function will be removed in future versions of sjmisc and has  been moved to package 'sjlabelled'. Please use sjlabelled::get_label() instead.*

still appears. Is this intended? The behavior is a little confusing to me.

**Comment by strengejacke** [comment]
I have to update packages stepwise. sjPlot is not updated on CRAN yet, so it still calls sjmisc. sjstats is submitted, ggeffects is prepared for submission, after that, sjPlot will follow. However, I plan some major revisions according the code-base, so this may still take some time until sjPlot is ready to submit.

**Comment by methodds** [comment]
I see, I guess the major revisions are due to relying on ggeffects for a majority of the sjp model plots?

**Comment by strengejacke** [comment]
yes, this is one reason. Another one is that I want the code base to be more generic and remove redundant code parts. I'm thinking of something like `sjp.model()` or `plot_model()`, which covers all object-classes, instead one sjp.lm for linear models, sjp.lmer for mixed models etc.

I would also like to make the code base of table functions easier and more generic, so I don't need so much duplicated code.

But maybe I'll address some other issues (the github-issue for sjPlot) first - sjPlot itself is working fine, so revising the code-base is not urgent.

**Comment by methodds** [comment]
Ok, thanks for the clarification, this can be closed then imo. For the transition  timeframe I will  just tell my students to ignore the deprecation messages that are shown for some of the sjPlot commands.
