### ISSUE TITLE
Error : object 'get_note' is not exported by 'namespace:sjlabelled'

### ISSUE THREAD

**Issue by rmn80** [strengejacke/sjlabelled#14]
I have got this error when installing package sjPLot_2.4.1 or older versions:

Error : object 'get_note' is not exported by 'namespace:sjlabelled'
ERROR: lazy loading failed for package 'sjPlot'

I have installed other versions of sjlabelled but it does not work. I know there a new release for sjPlot, but I really need to use an older version.
Thanks in advance.

**Comment by strengejacke** [comment]
Then you need to install an older version of _sjlabelled_ as well - I have removed the `get_note()` function from sjlabelled some time ago (see news: https://cran.r-project.org/web/packages/sjlabelled/news/news.html)
