### ISSUE TITLE
set_label does not overwrite variable label

### ISSUE THREAD

**Issue by cschwem2er** [strengejacke/sjlabelled#18]
Hi,

trying to use ``set_label`` in the example below does not override the ``variable label``:

```
d <- read_stata('GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta')
get_label(d$q119a)

"Parteiidentifikation (Version A)"


cdu <- rec(d$q119a, '1:3=1; else=0')
staerke <- rec(d$q120, '1=5; 2=4; 3=3; 4=2; 5=1; -97=0')
d$cdu_pid <- cdu * staerke %>% set_labels(
  c('keine PID' = 0, 'starke PID' = 5))  %>%  set_label('PID CDU/CSU')
get_label(d$cdu_pid)

"Parteiidentifikation (Version A)"
```

**Comment by marianschmidt** [comment]
Are you sure that `d$cdu_pid <- cdu * staerke %>% set_labels()`  is supposed to label `d$cdu_pid`? I am not an expert on pipes, but to my reading `cdu * staerke` would be passed on as the object to set_labels instead of `d$cdu_pid` which you actually want to label.

**Comment by strengejacke** [comment]
Makes sense to me. Maybe I can close this issue now...

**Comment by cschwem2er** [comment]
Makes sense to me too, thanks for the hint :)
