### ISSUE TITLE
Using set_labels function in a for-loop

### ISSUE THREAD

**Issue by marianschmidt** [strengejacke/sjlabelled#2]
I have spend some time trying to figure out, how to use the sjlabelled package in loops, so that I can automatically apply labels from a codeplan (e.g. list of variable and value labels defined in an excel file) to an R dataframe. The problem so far is that I cannot manage to use the set_label and set_labels functions in for loops or in R functions. 

As an example, lets assume we would like to label variables 1,2, and 3 for a dataframe (columns 1,2 and 3) and formats are given in a single vector called formats$allvallabels (e.g. "1=Male, 2=Female, 9=Unknown".

```
for(i in 1:3) {
  if (!is.na(formats$`Value labels`[i]) & formats$`Value labels`[i]=="yes") {
    data[,i] <- set_labels(data[,i], labels=eval(parse(text = paste("c(",formats$allvallabels[i], ")"))))
  }
}
```

does not work. There is no error message, but also the dataframe "data" remains unchanged.

However, using the exact same code and explicitly defining i=1, i=2, i=3 to loop through the variables (i.e. lines of the formatting/codeplan tabel) works:

```
i <- 1
if (!is.na(formats$`Value labels`[i]) & formats$`Value labels`[i]=="yes") {
  data[,i] <- set_labels(data[,i], labels=eval(parse(text = paste("c(",formats$allvallabels[i], ")"))))}
i <- 2
if (!is.na(formats$`Value labels`[i]) & formats$`Value labels`[i]=="yes") {
  data[,i] <- set_labels(data[,i], labels=eval(parse(text = paste("c(",formats$allvallabels[i], ")"))))}
i <- 3
if (!is.na(formats$`Value labels`[i]) & formats$`Value labels`[i]=="yes") {
  data[,i] <- set_labels(data[,i], labels=eval(parse(text = paste("c(",formats$allvallabels[i], ")"))))}

```
Do you have any explanation or workaround for this?

**Comment by strengejacke** [comment]
You don't need a loop, `labels` can be a list:

```
tmp <- data.frame(
  a = c(1, 2, 3),
  b = c(1, 2, 3),
  c = c(1, 2, 3)
)

labels <- list(
  c("one", "two", "three"),
  c("eins", "zwei", "drei"),
  c("un", "dos", "tres")
)

tmp <- set_labels(tmp, labels = labels)
str(tmp)
```

**Comment by marianschmidt** [comment]
I assume this only works if all columns in a data.frame are labeled through the list? In the example above, value labels are only used for selective columns. Of course I could use some generic labels like "Missing=-9", but still this would create some warnings for those columns of the data.frame that are character data types.
Anyway, I just wanted to report this in case it was unintended behavior of the set_labels function that it stops working when used in loops or other functions.

**Comment by strengejacke** [comment]
You can use `dplyr::select()` to select specific columns, and then `sjmisc::replace_columns()` to replace these specific columns in the original data frame.

To address the bug, could you please provide a reproducible example?
