### ISSUE TITLE
remove_var_labels

### ISSUE THREAD

**Issue by andresimi** [strengejacke/sjlabelled#23]
Hi,
I think it would be nice if we have separate functions to remove variable (remove_var_label) and value labels (remove_val_label). I think it would be useful in constructing tables when the variable label is too large.

Thank you.

**Comment by strengejacke** [comment]
You can remove variable and value labels by setting the `label` resp. `labels` argument in `set_label()` or set_labels()` to `""`.

And there is already `remove_labels()` as a convenient wrapper for value labels.

**Comment by andresimi** [comment]
Actually, I was looking for a way to remove all variable labels and maintain the value labels. In set_label I need to define a label vector with the same colum number of the data.frame.

**Comment by strengejacke** [comment]
True, sorry for the mistake. I added a `remove_label()` function now.

**Comment by andresimi** [comment]
Thank you very much!
