### ISSUE TITLE
set_labells() has a label order issue

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjlabelled#28]
As shown in the practice, the label "22" in the example code cannot stay in the right place, compared to the result using ordered(labels=). 

[example data file here-- https://jumpshare.com/v/9P1DetXkvdpuYI9vnAkw+/TEDS2018.rda](https://jumpshare.com/v/9P1DetXkvdpuYI9vnAkw+/TEDS2018.rda)
[example code here-- https://jumpshare.com/v/SRaNm9MfFLY9xvv5MyiH+/issues02.rmd](https://jumpshare.com/v/SRaNm9MfFLY9xvv5MyiH+/issues02.rmd)

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by frankcsliu** [comment]
I did provide the data and code in my post.

**Comment by strengejacke** [comment]
I couldn't get the code running.

**Comment by frankcsliu** [comment]
here is the updated code: https://jmp.sh/HCWv4Vm+/issue.r
