### ISSUE TITLE
as_label() name collision with dplyr

### ISSUE THREAD

**Issue by dicorynia** [strengejacke/sjlabelled#32]
Hi
Thanks for this nice package !
More an information than an issue :

It seems that a recent (?) update in dplyr introduced a function named `as_label()`
If we use both packages we have to prefix the function with the package name.

Therefore some code in the vignette has failed :
https://cran.r-project.org/web/packages/sjlabelled/vignettes/labelleddata.html
_e. g._ in § _Adding value labels as factor values_
```barplot(
  table(as_label(efc$e42dep),
        as_label(efc$e16sex)), 
  beside = T, 
  legend.text = T
)
```
![index](https://user-images.githubusercontent.com/31208891/73645575-d9f53600-4677-11ea-9819-477239453208.png)

But the same in
https://strengejacke.github.io/sjlabelled/articles/labelleddata.html is still fine

![unnamed-chunk-5-1](https://user-images.githubusercontent.com/31208891/73645675-03ae5d00-4678-11ea-9d6b-59422cf81dbd.png)

**Comment by strengejacke** [comment]
Thanks, I hope this issue is fixed now!
