### ISSUE TITLE
remove_labels does not work when factor levels are strings

### ISSUE THREAD

**Issue by iago-pssjd** [strengejacke/sjlabelled#34]
When I try to remove an `sj`-label with `sjlabelled::remove_labels` from a factor whose levels are not numbers, but strings, all labels are deleted with a warning message (something like `NA's introduced by coercion`).

**Comment by strengejacke** [comment]
Do you have a reproducible example?

**Comment by iago-pssjd** [comment]
Yes.
```
z <- factor(LETTERS[3:1], ordered = TRUE)
z <- sjlabelled::set_labels(z, labels = c("yes", "maybe", "no"))
sjlabelled::remove_labels(z, labels = 2)
```
