### ISSUE TITLE
as_labeld(data,drop.na=FALSE) changed from version 1.1.3 to version 1.1.6, intended?

### ISSUE THREAD

**Issue by Slothhead** [strengejacke/sjlabelled#41]
Thanks for the nice package and sorry, for the email we have written before. We just figured out that the correct way to report bugs is to write you a message here. Not sure, if the following thing we found is really a bug or if it was intended:

In the 1.1.3 version sjlabelled package, the following argument "as_label(data, drop.na=FALSE)" was keeping user-defined missing labels in the data-set and converting the values of variables to their labels. However, this is changed in the current version, which 1.1.6. With the last version, "drop.na=FALSE" deletes the user-defined missing labels and merges them into system-missings. That is why we had to change our code to drop.na=TRUE so we keep the user-defined missing labels in our dataset, when converting the values to their associated labels. Could you please let us know if this was intended?

Best wishes,
Ann-Kristin (and Team)

**Comment by strengejacke** [comment]
I replied to your colleague, who sent me an email, however, I don't have the sent email at hand (maybe you can ask him for the detailed answer).

In short: due to https://github.com/strengejacke/sjlabelled/pull/35, I had to remove this functionality, at least temporary.
