### ISSUE TITLE
Please consider set F as default for as.num and atomic.to.fac

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjlabelled#45]
I have been using survey/poll data with sjlabelled and wondering if it better serves users who are dealing with facotrs (previous spss users). 

It will save much of time of tuning it back everytime when cleaning and recoding variables. 

Hopefully, the two arguments will be reconsidered to set to: 
as.num = F 
atomic.to.fac = F

Thank you.

**Comment by strengejacke** [comment]
Not sure which functions you are referring to. For the `read_*()` functions, `atomic.to.fac = FALSE` is already the default.

**Comment by frankcsliu** [comment]
Sorry I meant 

as.num=F for sjmisc::rec()

and 
atomic.to.fac=T for read_*()
