### ISSUE TITLE
sjPlot::view_df: error while processing a data set  imported via sjlabelled::read_spss

### ISSUE THREAD

**Issue by frankcsliu** [strengejacke/sjlabelled#5]
I double checked this issue with two data sets that worked before. The below message continue to appear: 

"Error in sprintf("%i", range(x[[index]], na.rm = T)) : invalid format '%i'; use format %f, %e, %g or %a for numeric objects"

Please help. Thank you, Daniel.

Best, 
Frank

**Comment by strengejacke** [comment]
This issue might be solved in the latest GitHub Version of sjPlot. Could you please provide a reproducible example or check the latest sjPlot Dev-version?

**Comment by frankcsliu** [comment]
I used "devtools::install_github("strengejacke/strengejacke")" to reinatalled the packages. and use the data file id15 (http://jmp.sh/xfcyzRk). but it did not work. the same error message came out. 
The encoding of the data is big5.

**Comment by strengejacke** [comment]
can't reproduce, I can open and view the file w/o any error. I think this requires the forthcoming sjPlot update, which will be available within the next 1-2 weeks.
