### ISSUE TITLE
R session aborted when trying to import a .dta file

### ISSUE THREAD

**Issue by jobreu** [strengejacke/sjlabelled#50]
The R session is aborted in RStudio when I try to read a .dta file using `read_stata()`. I am using R version 4.1.0 and sjlabelled version 1.1.8 with Windows 10 as OS. The file has been generated with Stata version 15. This [Stackoverflow post](https://stackoverflow.com/questions/67288533/am-i-the-only-one-experiencing-problems-with-rs-haven-package) suggests that this may be related to changes in ReadStat which haven makes use of (I have also commented on a similar [issue](https://github.com/tidyverse/haven/issues/600) that has been opened for haven).

**Comment by strengejacke** [comment]
It indeed seems to be an issue related to haven/ReadStata, not sjlabelled, so will close in favor of the other issues opened in the haven-repository.
