### ISSUE TITLE
How to make sure that only the coefficient names - and not the terms - will be shown in the label 

### ISSUE THREAD

**Issue by FabiolaEto** [strengejacke/sjlabelled#9]
Hi,

I've plotted a `plot_model` picking specific `terms` from the plot. However, when I plot it, it shows the _coefficients names_ preceded by the _terms names_ as you can see below.

> levels(b4$sexo2)
> [1] "fem"  "masc"
> levels(b4$raca2)
> [1] "branca"   "parda"    "preta"    "amarela"  "indigena"
> levels(b4$escol2)
> [1] "universitario" "2º grau"       "< 2º grau"    
> levels(b4$rendacat2)
> [1] "3" "2" "1"

![plot_model](https://user-images.githubusercontent.com/37416303/42223397-0889758c-7eae-11e8-8cf7-2e5ace8fa0d0.PNG)

I wanted only the _coefficients names_ in the label, like in the document where you described how to plot estimates of regression models. 

E.g. you shown how to keep only coefficients `sex2`, `dep2` and `dep3`

> plot_model(m1, terms = c("sex2", "dep2", "dep3"))

However, the plot axis show different labels from those specified. Instead of showing  `sex2`, `dep2` and `dep3` it shows `slightly dependent`, `moderately dependent` and `female`.

![e g](https://user-images.githubusercontent.com/37416303/42223503-4d1d4aca-7eae-11e8-913b-cfea2cf6ca57.PNG)

**Comment by strengejacke** [comment]
The names of the coefficients - i.e. what you get when you call `summary(model)` or `coef(model)` - for factors are _variable name_ + _level_. You can change the labels for the y-axis using the `axis.labels`-argument from `plot_model()`, or [label your data](https://strengejacke.github.io/sjlabelled/).

**Comment by FabiolaEto** [comment]
Thank you very much! It worked by using `axis.labels = c( )`
